pretrain:
  data_dir: /path/to/data
  output_dir: /path/to/output
  batch_size: 8
  learning_rate: 8e-4
  num_epochs: 200
  warmup_epochs: 10
  num_workers: 2

align:
  data_dir: /path/to/data
  output_dir: /path/to/output
  label_file: /path/to/labels.csv
  batch_size: 8
  learning_rate: 8e-4
  num_epochs: 200
  warmup_epochs: 10
  num_workers: 2

downstream_eval:
  data_dir: /path/to/data
  model_dir: /path/to/pretrained/model
  train_label_file: /path/to/train_labels.csv
  test_label_file: /path/to/test_labels.csv
  batch_size: 8
  learning_rate: 1e-4
  num_epochs: 30
  warmup_epochs: 5
  num_workers: 2
  eval_interval: 5
  eval_type: fine_tune
  dataset: UCF101
