name: human_removal
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - opencv
  - pytorch=2.3.0
  - torchvision=0.18.0
  - cudatoolkit=12.2
  - pip:
    - mediapipe
    - pyyaml==5.1
    - git+https://github.com/facebookresearch/detectron2.git
